version: "3.9"

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - mlflow
      - db

  mlflow:
    image: python:3.11-slim
    command: >
      bash -c "pip install mlflow==2.8.0 && mlflow server
               --host 0.0.0.0
               --port 5000
               --default-artifact-root /mlflow/artifacts"
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookrec
    ports:
      - "5432:5432"

volumes:
  mlflow_data:
